version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/tomcat/webapps/
    overwrite : yes    
permissions:
  - object: /usr/local/tomcat/webapps/
    pattern: "*"
    owner: root
    mode: 777
    type:
      - file
hooks:
  ApplicationStop:
    - location: scripts/stop_tomcat.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before_deploy.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_tomcat.sh
      timeout: 300
      runas: root
